# Generated by Django 6.1 on 2026-09-03 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('degree_level', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('masters', "Master's"), ('phd', 'PhD')], max_length=20)),
                ('funding_type', models.CharField(choices=[('full', 'Fully Funded'), ('partial', 'Partially Funded')], max_length=10)),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('required_documents', models.TextField(blank=True)),
                ('application_link', models.URLField()),
                ('is_published', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='myapp.country')),
            ],
        ),
    ]
