# Generated by Django 6.1 on 2026-09-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_scholarship_is_featured_alter_scholarship_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
    ]
