# Generated by Django 6.1 on 2026-09-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_country_slug_alter_scholarship_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('country_name', models.CharField(max_length=100)),
                ('degree_level', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('masters', "Master's"), ('phd', 'PhD')], max_length=20)),
                ('funding_type', models.CharField(choices=[('full', 'Fully Funded'), ('partial', 'Partially Funded')], max_length=10)),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('required_documents', models.TextField(blank=True)),
                ('application_link', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='scholarship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scholarships/'),
        ),
    ]
