# Generated by Django 6.1 on 2026-09-13 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_newslettersubscriber_unsubscribe_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('scholarship_view', 'Scholarship View'), ('application_click', 'Application Click'), ('search', 'Search / Filter'), ('save', 'Scholarship Saved')], db_index=True, max_length=20)),
                ('page_path', models.CharField(blank=True, max_length=255)),
                ('search_summary', models.CharField(blank=True, max_length=255)),
                ('result_count', models.PositiveIntegerField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('referrer', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scholarship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='myapp.scholarship')),
            ],
        ),
    ]
