# Generated by Django 6.1 on 2026-09-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_analyticsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='deadline_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
