# Generated by Django 6.1 on 2026-09-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_scholarship_deadline_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='country',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
